### ISSUE TITLE
extension popup delays on connect  

### ISSUE THREAD

**Issue by TalDerei** [prax-wallet/prax#195]
@grod220, you mentioned previously that the connection popup seemed more responsive, but I'm actually noticing the opposite —a delay when connecting the wallet. Also, it looks like we're skipping the [numeraire](https://github.com/prax-wallet/prax/blob/main/apps/extension/src/routes/page/onboarding/set-numeraire.tsx) step during onboarding?

https://github.com/user-attachments/assets/92866535-608d-4ffa-94fd-a4ac45578290

**Comment by grod220** [comment]
The reason connect is delayed is because the genesis sync is blocking the thread with a long running process. After we move this off the main thread into the offscreen client, this will be resolved automatically.

The reason why the numeraires step is being skipped is because we have not defined numeraires [for mainnet](https://github.com/prax-wallet/registry/blob/main/registry/chains/penumbra-1.json#L1517). It's not super clear to me the selection process for this, will create another issue representing selection and enabling of that.
